{
 "title": "Kubernetes Geral",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "Workloads"
    },
    { "expr": "count(kube_pod_info)", "legendFormat": "PODs" },
    {
     "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "Control Planes"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info)",
     "legendFormat": "Nodes"
    },
    {
     "expr": "count(kube_node_info) - count(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Workers"
    },
    {
     "expr": "count(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Control Plane"
    }
   ]
  },
  {
   "title": "Total POD CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", node=~\"$node\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total POD CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", node=~\"$node\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total POD RAM Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", node=~\"$node\"}) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total POD RAM Limits",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", node=~\"$node\"}) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Resources by Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$node\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container !=\"\", resource=\"cpu\", node=~\"$node\" }) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container !=\"\", resource=\"cpu\", node=~\"$node\" }) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container !=\"\", resource=\"memory\", node=~\"$node\" }) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container !=\"\", resource=\"memory\", node=~\"$node\" }) by (node)"
    }
   ]
  },
  {
   "title": "Resources by PODs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", container !=\"\", resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\" }) by (pod, container,node, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", container !=\"\",resource=\"cpu\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", container !=\"\", resource=\"memory\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", container !=\"\", resource=\"memory\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}[$__rate_interval])) by  (pod, container, node, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace) "
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"$pod\", container !=\"\", namespace=~\"$namespace\"}) by  (pod, container, namespace) "
    },
    {
     "expr": "time() - kube_pod_created{pod=~\"$pod\", container !=\"\", namespace=~\"$namespace\"} * on(pod) group_right kube_pod_container_info{pod=~\"$pod\",container !=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace) / \r\nsum(kube_pod_container_resource_limits{pod=~\"$pod\", container !=\"\", resource=\"memory\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace))*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}[$__rate_interval])) by  (pod, container, node, namespace))/\r\n(sum(kube_pod_container_resource_limits{pod=~\"$pod\", container !=\"\", resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\" }) by (pod, container,node, namespace))*100 \r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}[$__rate_interval])) by  (pod, container, node, namespace)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\", container !=\"\", node=~\"$node\",namespace=~\"$namespace\"}) by  (pod, container, node, namespace)  ",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}